### ISSUE TITLE
Hardcoded variable in main

### ISSUE THREAD

**Issue by certanet** [anthonyspiteri/terraform#1]
The apply currently fails due to the resource pool being hardcoded instead of referencing the variable:

https://github.com/anthonyspiteri/terraform/blob/1486cbe3b4bad95cef3b92634ef6e4108e4c32f8/deploy_kubernetes_CentOS/main.tf#L35

Changing to the below works fine:
```
name          = "${var.vsphere_vm_resource_pool}"
```

**Comment by anthonyspiteri** [comment]
Hey there. Just picked this up and have fixed it. Appreciated.
